//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TseTmc.TseTest {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8855/", ConfigurationName="TseTest.AucWebServiceSoap")]
    public interface AucWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/MessageList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MessageList(string UsrNam, string UsrPwd, int Idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/MessageList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MessageListAsync(string UsrNam, string UsrPwd, int Idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/AuctionConfirmByCDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AuctionConfirmByCDS(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/AuctionConfirmByCDS", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AuctionConfirmByCDSAsync(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/InstrumentConfirmByCDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InstrumentConfirmByCDS(string UsrNam, string UsrPwd, int InstrumentId, bool Confirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/InstrumentConfirmByCDS", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InstrumentConfirmByCDSAsync(string UsrNam, string UsrPwd, int InstrumentId, bool Confirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/ConfirmAuctionAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ConfirmAuctionAccount(string UsrNam, string UsrPwd, int AuctionAccountId, int Confirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/ConfirmAuctionAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ConfirmAuctionAccountAsync(string UsrNam, string UsrPwd, int AuctionAccountId, int Confirm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AucWebServiceSoapChannel : TseTmc.TseTest.AucWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AucWebServiceSoapClient : System.ServiceModel.ClientBase<TseTmc.TseTest.AucWebServiceSoap>, TseTmc.TseTest.AucWebServiceSoap {
        
        public AucWebServiceSoapClient() {
        }
        
        public AucWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AucWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AucWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AucWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet MessageList(string UsrNam, string UsrPwd, int Idn) {
            return base.Channel.MessageList(UsrNam, UsrPwd, Idn);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MessageListAsync(string UsrNam, string UsrPwd, int Idn) {
            return base.Channel.MessageListAsync(UsrNam, UsrPwd, Idn);
        }
        
        public bool AuctionConfirmByCDS(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc) {
            return base.Channel.AuctionConfirmByCDS(UsrNam, UsrPwd, AuctionIdn, Confirm, CDSDesc);
        }
        
        public System.Threading.Tasks.Task<bool> AuctionConfirmByCDSAsync(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc) {
            return base.Channel.AuctionConfirmByCDSAsync(UsrNam, UsrPwd, AuctionIdn, Confirm, CDSDesc);
        }
        
        public bool InstrumentConfirmByCDS(string UsrNam, string UsrPwd, int InstrumentId, bool Confirm) {
            return base.Channel.InstrumentConfirmByCDS(UsrNam, UsrPwd, InstrumentId, Confirm);
        }
        
        public System.Threading.Tasks.Task<bool> InstrumentConfirmByCDSAsync(string UsrNam, string UsrPwd, int InstrumentId, bool Confirm) {
            return base.Channel.InstrumentConfirmByCDSAsync(UsrNam, UsrPwd, InstrumentId, Confirm);
        }
        
        public bool ConfirmAuctionAccount(string UsrNam, string UsrPwd, int AuctionAccountId, int Confirm) {
            return base.Channel.ConfirmAuctionAccount(UsrNam, UsrPwd, AuctionAccountId, Confirm);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmAuctionAccountAsync(string UsrNam, string UsrPwd, int AuctionAccountId, int Confirm) {
            return base.Channel.ConfirmAuctionAccountAsync(UsrNam, UsrPwd, AuctionAccountId, Confirm);
        }
    }
}
