//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TseTmc.TseTmcService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8855/", ConfigurationName="TseTmcService.AucWebServiceSoap")]
    public interface AucWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/MessageList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MessageList(string UsrNam, string UsrPwd, int Idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/MessageList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MessageListAsync(string UsrNam, string UsrPwd, int Idn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/ChkUsrLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChkUsrLogin(string UsrNam, string UsrPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/ChkUsrLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChkUsrLoginAsync(string UsrNam, string UsrPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/AuctionConfirmByCDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AuctionConfirmByCDS(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8855/AuctionConfirmByCDS", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AuctionConfirmByCDSAsync(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AucWebServiceSoapChannel : TseTmc.TseTmcService.AucWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AucWebServiceSoapClient : System.ServiceModel.ClientBase<TseTmc.TseTmcService.AucWebServiceSoap>, TseTmc.TseTmcService.AucWebServiceSoap {
        
        public AucWebServiceSoapClient() {
        }
        
        public AucWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AucWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AucWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AucWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet MessageList(string UsrNam, string UsrPwd, int Idn) {
            return base.Channel.MessageList(UsrNam, UsrPwd, Idn);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MessageListAsync(string UsrNam, string UsrPwd, int Idn) {
            return base.Channel.MessageListAsync(UsrNam, UsrPwd, Idn);
        }
        
        public string ChkUsrLogin(string UsrNam, string UsrPwd) {
            return base.Channel.ChkUsrLogin(UsrNam, UsrPwd);
        }
        
        public System.Threading.Tasks.Task<string> ChkUsrLoginAsync(string UsrNam, string UsrPwd) {
            return base.Channel.ChkUsrLoginAsync(UsrNam, UsrPwd);
        }
        
        public bool AuctionConfirmByCDS(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc) {
            return base.Channel.AuctionConfirmByCDS(UsrNam, UsrPwd, AuctionIdn, Confirm, CDSDesc);
        }
        
        public System.Threading.Tasks.Task<bool> AuctionConfirmByCDSAsync(string UsrNam, string UsrPwd, int AuctionIdn, bool Confirm, string CDSDesc) {
            return base.Channel.AuctionConfirmByCDSAsync(UsrNam, UsrPwd, AuctionIdn, Confirm, CDSDesc);
        }
    }
}
